1. Qual a diferença entre uma variável tipo int e uma tipo float?

Uma variável do tipo int é utilizada para guardar valores inteiros, sejam eles positivos ou negativos. Por exemplo, você pode guardar o número de vezes que um carro azul passou na frente da sua casa numa variável do tipo int.
Já uma variável do tipo float é utilizada para guardar valores decimais, ou seja, números reais. 
A diferença entre estes dois tipos está relacionada à precisão, pois o tipo float possui precisão de 6 casas decimais, enquanto que o tipo int não possui casas decimais representando a precisão do valor.

2. O que é uma variável do tipo string?

É uma variável que guarda uma sequência de caracteres, como um nome ou uma frase inteira, contendo diversos caracteres. Ela é criada entre aspas simples ou duplas.

Exemplos: 

'Hello, World!'

'Este número, o 5, também é uma string'


3. Crie uma função que encontre o maior valor entre 3 números imputados pelo usuário.

In [18]:
def findGreaterValue(*values):
    greater = -999999999
    for value in values:
        if value > greater:
            greater = value
    return greater

greater_value = findGreaterValue(23, 1, 32)
print(greater_value)

32


4. Crie uma função que identifique se duas palavras inseridas pelo usuário são anagramas.

In [ ]:
def identifyAnagram(word1, word2):
    output = True
    while(output):
        word1 = ''.join(sorted(word1.lower()))
        print(word1, word2)
        if word1 == word2.lower():
            output = False
        else:
            output = True
    print(word1, word2)
    
print(identifyAnagram('acot', 'toca'))

5. Crie uma função que retorne a contagem de consoantes e vogais de uma palavra imputada pelo usuário.

In [20]:
def countVowelConsonant(word):
    vowels = 'aeiou'
    count_vowel = 0
    count_consonant = 0
    for letter in word:
        if letter in vowels:
            count_vowel += 1
        else:
            count_consonant += 1
    return count_vowel, count_consonant

word = 'otorrinolaringologista'
num_vowel, num_consonant = countVowelConsonant(word)
print(f'The word {word} has {num_vowel} vowels and {num_consonant} consonants')

The word otorrinolaringologista has 10 vowels and 12 consonants


6. O que são dicionários em Python?

São uma forma de organizar os dados. Nesse caso, os dados são estruturados em pares chave-valor, por exemplo: 

nome: 'Marcelo'

Na estrutura geral, ele fica assim:

dict = {

    chave1: valor1,

    chave2: valor2,

    chave3: valor3
    
}

Você acessa os valores de um dicionário através de suas chaves, como no exemplo a seguir:

valor1_do_dict = dict['chave1']


Se você quer adicionar algum valor, você simplesmente faz o seguinte:

dict['chave1'] = 'valor_aleatorio'

Agora, se você quer remover um valor, você faz isso:

dict.pop('chave1')

7. Crie uma lista com os 100 mil primeiros números naturais na sequência (i.e., de 1 à 100000). Salve esta lista em um objeto com nome cem_mil_lista. Inicie então uma lista vazia chamada numeros_pares. A partir da lista cem_mil_lista, salve todos os %%valores pares na lista numeros_pares. Resolva este exercício de duas formas: a primeira utilizando um loop com o for e a segunda com list comprehension. Compare o tempo de execução das duas.
* Para comparar o tempo de execução, insira na primeira linha da célula %%time.

In [21]:
%%time
cem_mil_lista = []
even_numbers = []
for i in range(1, 100001):
    cem_mil_lista.append(i)
    if i % 2 == 0:
        even_numbers.append(i)

CPU times: total: 15.6 ms
Wall time: 24.1 ms


In [22]:
%%time
cem_mil_lista = [i for i in range(1, 100001)]
even_numbers = [i for i in cem_mil_lista if i % 2 == 0]

CPU times: total: 15.6 ms
Wall time: 10.5 ms


8. Para que serve o argumento Kwargs nas funções?

Quando você deseja utilizar uma função com paramêtros arbitrários, ou seja, que não são pré estabelecidos, você utiliza *args para passar uma tupla. Beleza, mas e o kwargs? O kwargs segue a mesma ideia, mas ao invés de passar uma tupla, você passa um dicionário, contendo os pares chave-valor característicos. 

9. Escreva um programa em Python para encontrar os números que são divisíveis por 7 e múltiplos de 5, entre 1500 e 2700 (ambos incluídos). Em outras palavras, combine o que você aprendeu de loop e condicional para criar uma lista de valores que atendam às condições exigidas.

In [1]:
my_numbers = []
for number in range(1500, 2701):
    if number % 7 == 0 and number % 5 == 0:
        my_numbers.append(number)

print(my_numbers)


[1505, 1540, 1575, 1610, 1645, 1680, 1715, 1750, 1785, 1820, 1855, 1890, 1925, 1960, 1995, 2030, 2065, 2100, 2135, 2170, 2205, 2240, 2275, 2310, 2345, 2380, 2415, 2450, 2485, 2520, 2555, 2590, 2625, 2660, 2695]


10. Escreva um programa Python para construir o padrão a seguir, usando um número de loop aninhado. 

Ir para o editor

Saída esperada:

1

22

333

4444

55555

666666

7777777

88888888

999999999


In [4]:
for number in range(1,10):
    print(str(number)*number)

1
22
333
4444
55555
666666
7777777
88888888
999999999


11. Escreva um programa em Python para verificar se um alfabeto é uma vogal ou uma consoante. Ir para o editor

Saída esperada:

Insira uma letra do alfabeto: m

m é uma consoante.


In [16]:
def verifyVowelConsonant(letter):
    vowels = 'aeiou'
    if letter in vowels:
        print(f'{letter} é uma vogal')
    else:
        print(f'{letter} é uma consoante')

verifyVowelConsonant(input('Insira uma letra do alfabeto: ')) 

t é uma consoante


(PARTE 3) Bibliotecas e Numpy:

In [1]:
import numpy as np

12. Para que serve o PIP no Python?

O PIP serve para gerenciar os pacotes do Python, sendo assim, ele executa funções como a de instalar pacotes, removê-los, atualizá-los ou listá-los. Em outras palavras, é com o PIP que você consegue obter tudo aquilo que você precisa para rodar seus projetos em Python.

13. Crie um array com 10 números no formato float. Converta-os para o formato inteiro.


In [5]:
array_ten = np.arange(10, dtype=float)
integer_array = array_ten.astype(int)
print(array_ten)
print(integer_array)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


14. Converta o array abaixo para o formato booleano.

a = np.array([[1,0,1],[1,1,1],[0,0,0]])


In [9]:
a = np.array([[1,0,1],[1,1,1],[0,0,0]])
boolean_array = a.astype(bool)
boolean_array

array([[ True, False,  True],
       [ True,  True,  True],
       [False, False, False]])

15. Empilhe horizontalmente os arrays abaixo.

a = np.array([[10,20,15],[0,0,20]])

b = np.array([[15,7,3],[5,5,8]])

In [11]:
a = np.array([[10,20,15],[0,0,20]])
b = np.array([[15,7,3],[5,5,8]])

#first method
c = np.concatenate([a,b], axis=1)
print(c, '\n')

#second method
c = np.hstack([a,b])
print(c, '\n')

#third method
c = np.c_[a,b]
print(c)

[[10 20 15 15  7  3]
 [ 0  0 20  5  5  8]] 

[[10 20 15 15  7  3]
 [ 0  0 20  5  5  8]] 

[[10 20 15 15  7  3]
 [ 0  0 20  5  5  8]]


16. Empilhe verticalmente os arrays do exercício 15. (Usem o np.vstack)

In [12]:
#first method
c = np.concatenate([a,b], axis=0)
print(c, '\n')

#second method
c = np.vstack([a,b])
print(c, '\n')

#third method
c = np.r_[a,b]
print(c)

[[10 20 15]
 [ 0  0 20]
 [15  7  3]
 [ 5  5  8]] 

[[10 20 15]
 [ 0  0 20]
 [15  7  3]
 [ 5  5  8]] 

[[10 20 15]
 [ 0  0 20]
 [15  7  3]
 [ 5  5  8]]


17. Gere uma lista de números inteiros que vão de 0 a 100, de 2 em 2, e, na sequência, converta essa lista em um array.

In [13]:
even_numbers = np.arange(0,100,2)
even_numbers

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

18. Gere uma lista de valores que vão de 5 a 10 de 0.5 em 0.5.

In [14]:
decimal_numbers = np.arange(5,10,0.5)
decimal_numbers

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

19. Crie um array 3x3 cujos valores seguem uma distribuição normal.

In [15]:
array_3x3 = np.random.randn(3,3)
array_3x3

array([[ 0.6172167 , -0.05037315, -0.10181611],
       [ 0.41980963, -0.86175854, -0.06748603],
       [-0.28076913,  0.88391588, -0.21038619]])

20. Como calcular o determinante de uma matriz no Numpy?

In [17]:
#Podemos fazer isso utilizando a função det() do módulo linalg do numpy
det = np.linalg.det(array_3x3)
det

0.1301707280200646